/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Frames;

import java.sql.DriverManager;
import java.sql.Connection;
import java.sql.Statement;
import java.sql.ResultSet;
import javax.swing.JOptionPane;
import Components.DBConnector;

/**
 *
 * @author kishanbhakta
 */
public class Startup_Frame extends javax.swing.JFrame {
public String aa;
    /**
     * Creates new form Startup_Frame
     */
    public Startup_Frame(String a) {
        initComponents();
        aa = a;
        if(aa.isEmpty()){
            UNAME_lable.setText("");
            jList1.setVisible(false);   
            rem.setVisible(false);
            Meds_Button.setVisible(false);
            psf.setVisible(false);

            Rehab_Button.setVisible(false);
            
        }
        else{
            UNAME_lable.setText("Hello "+aa);
            jList1.setVisible(true);
            rem.setVisible(true);
            Meds_Button.setVisible(true);
            psf.setVisible(true);

            Rehab_Button.setVisible(true);
            Login_Button.setText("Log out");
        }
    }
        

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        psf = new javax.swing.JLabel();
        Rehab_Button = new javax.swing.JButton();
        Meds_Button = new javax.swing.JButton();
        Login_Button = new javax.swing.JButton();
        UNAME_lable = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jList1 = new javax.swing.JList<>();
        rem = new javax.swing.JLabel();
        QuitButton = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Patient Portal");

        psf.setText("Please select one of the following:");

        Rehab_Button.setText("Rehab Journals");
        Rehab_Button.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Rehab_ButtonActionPerformed(evt);
            }
        });

        Meds_Button.setText("Meds");
        Meds_Button.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Meds_ButtonActionPerformed(evt);
            }
        });

        Login_Button.setText("Login");
        Login_Button.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Login_ButtonActionPerformed(evt);
            }
        });

        UNAME_lable.setText("jLabel1");

        jList1.setModel(new javax.swing.AbstractListModel<String>() {
            String[] strings = { "Reminder Example 1", "Reminder Example 2", "Reminder Example 3", "Reminder Example 4" };
            public int getSize() { return strings.length; }
            public String getElementAt(int i) { return strings[i]; }
        });
        jScrollPane1.setViewportView(jList1);

        rem.setText("Reminders:");

        QuitButton.setText("Quit");
        QuitButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                QuitButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                .addComponent(Rehab_Button)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(Meds_Button))
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                .addGap(1, 1, 1)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(rem)
                                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 382, javax.swing.GroupLayout.PREFERRED_SIZE))))
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(psf)
                            .addComponent(Login_Button))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(QuitButton)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(layout.createSequentialGroup()
                .addGap(144, 144, 144)
                .addComponent(UNAME_lable)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(UNAME_lable)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Login_Button)
                    .addComponent(QuitButton))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(psf)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Rehab_Button)
                    .addComponent(Meds_Button))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(rem)
                .addGap(5, 5, 5)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void Rehab_ButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Rehab_ButtonActionPerformed
        // TODO add your handling code here:

        Login_Page lp = new Login_Page();
        Drugs_Page dp = new Drugs_Page(aa);
        Meds_Page mp = new Meds_Page(aa);
        mp.setVisible(false);
        dp.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_Rehab_ButtonActionPerformed

    private void Meds_ButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Meds_ButtonActionPerformed
        // TODO add your handling code here:


        Login_Page lp = new Login_Page();
        Drugs_Page dp = new Drugs_Page(aa);

        dp.setVisible(false);
        Meds_Page mp = new Meds_Page(aa);
        mp.setVisible(true);
        this.setVisible(false);
        System.out.println(aa);
    }//GEN-LAST:event_Meds_ButtonActionPerformed

    private void Login_ButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Login_ButtonActionPerformed
        // TODO add your handling code here:


        Login_Page lp = new Login_Page();

        Drugs_Page dp = new Drugs_Page(aa);
        if(Login_Button.getText()=="Login"){

            Meds_Page mp = new Meds_Page(aa);
            mp.setVisible(false);
            dp.setVisible(false);
            lp.setVisible(true);
            this.setVisible(false);
        }
        else if(Login_Button.getText()=="Log out"){
            UNAME_lable.setText("");
            jList1.setVisible(false);   
            rem.setVisible(false);
            Meds_Button.setVisible(false);
            psf.setVisible(false);

            Rehab_Button.setVisible(false);
            Login_Button.setText("Login");
        }
    }//GEN-LAST:event_Login_ButtonActionPerformed

    private void QuitButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_QuitButtonActionPerformed
        // TODO add your handling code here:
        JOptionPane.showMessageDialog(null, "Bye Bye");
        System.exit(0);
    }//GEN-LAST:event_QuitButtonActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Startup_Frame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Startup_Frame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Startup_Frame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Startup_Frame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        
        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                Startup_Frame sf = new Startup_Frame("");
                sf.setVisible(false);
                Login_Page lp = new Login_Page();
                lp.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Login_Button;
    private javax.swing.JButton Meds_Button;
    private javax.swing.JButton QuitButton;
    private javax.swing.JButton Rehab_Button;
    private javax.swing.JLabel UNAME_lable;
    private javax.swing.JList<String> jList1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel psf;
    private javax.swing.JLabel rem;
    // End of variables declaration//GEN-END:variables
}